import bcrypt from 'bcryptjs'; import {User} from '../models/User.js'; import {registerSchema,loginSchema} from '../validators/schemas.js'; import {ok,fail} from '../utils/api.js'; import {issueSession,rotateRefreshToken,revokeRefreshToken,REFRESH_COOKIE} from '../utils/tokens.js'; import {audit} from '../services/auditService.js';
const DUMMY_HASH='$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy';
function setRefresh(res,value){res.setHeader('Set-Cookie',`${REFRESH_COOKIE}=${encodeURIComponent(value)}; Max-Age=${Number(process.env.REFRESH_TOKEN_DAYS||7)*86400}; Path=/api/v1/auth; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`);}
function getRefresh(req){const raw=req.headers.cookie||''; const match=raw.split(';').map(v=>v.trim()).find(v=>v.startsWith(`${REFRESH_COOKIE}=`)); return match?decodeURIComponent(match.slice(REFRESH_COOKIE.length+1)):null;}
export async function register(req,res){const d=registerSchema.parse(req.body); const exists=await User.findOne({email:d.email}); if(exists)return fail(res,'Email already registered',409); const passwordHash=await bcrypt.hash(d.password,12); const user=await User.create({name:d.name,email:d.email,passwordHash}); const session=await issueSession(user); setRefresh(res,session.refreshToken); await audit({actor:user._id,action:'USER_REGISTERED',resource:'User',resourceId:user.id,requestId:req.id}); ok(res,{token:session.accessToken,user:{id:user._id,name:user.name,email:user.email,role:user.role}},201);}
export async function login(req,res){const d=loginSchema.parse(req.body); const user=await User.findOne({email:d.email}).select('+passwordHash'); if(user?.lockUntil && user.lockUntil>Date.now()) return fail(res,'Account temporarily locked; please try again later',429,'ACCOUNT_LOCKED'); const hash=user?.passwordHash||DUMMY_HASH; const valid=await bcrypt.compare(d.password,hash); if(!user||!valid){if(user){user.failedLoginAttempts=(user.failedLoginAttempts||0)+1; if(user.failedLoginAttempts>=5){const exponent=Math.min(user.failedLoginAttempts-5,5); user.lockUntil=new Date(Date.now()+Math.min(60,2**exponent)*60*1000);} await user.save();} return fail(res,'Invalid email or password',401,'INVALID_CREDENTIALS');} if(user.status!=='active')return fail(res,'Account disabled',403); user.failedLoginAttempts=0; user.lockUntil=null; await user.save(); const session=await issueSession(user); setRefresh(res,session.refreshToken); await audit({actor:user._id,action:'ADMIN_LOGIN',resource:'User',resourceId:user.id,requestId:req.id}); ok(res,{token:session.accessToken,user:{id:user._id,name:user.name,email:user.email,role:user.role}});}
export async function refresh(req,res){const session=await rotateRefreshToken(getRefresh(req)); if(!session)return fail(res,'Refresh session invalid or expired',401,'REFRESH_INVALID'); setRefresh(res,session.refreshToken); ok(res,{token:session.accessToken,user:{id:session.user._id,name:session.user.name,email:session.user.email,role:session.user.role}});}
export async function logout(req,res){await revokeRefreshToken(getRefresh(req)); res.setHeader('Set-Cookie',`${REFRESH_COOKIE}=; Max-Age=0; Path=/api/v1/auth; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`); if (req.user?._id) await audit({actor:req.user._id,action:'ADMIN_LOGOUT',resource:'User',resourceId:req.user._id,requestId:req.id}); ok(res,{loggedOut:true});}
export async function me(req,res){ok(res,{user:req.user});}
