import bcrypt from 'bcryptjs'; import {connectDb,disconnectDb} from '../config/db.js'; import {env} from '../config/env.js'; import {Product} from '../models/Product.js'; import {Category} from '../models/Category.js'; import {User} from '../models/User.js';
const products=[
['PR 114 Long Grain Parboiled Rice','non-basmati','Commercial long-grain PR variety processed through the mill parboiling workflow. Final broken percentage, moisture and polishing are agreed by buyer contract.','images/parboiled.webp',{'grainLength':'6.4–7.0 mm','moisture':'12–14%','broken':'Buyer contract: under 1%–25%+ grades'}],
['PR 126 Long Grain Parboiled Rice','non-basmati','Regional Punjab long-grain PR variety suitable for commercial bulk requirements, subject to seasonal procurement and agreed specifications.','images/parboiled.webp',{'grainLength':'6.4–7.0 mm','moisture':'12–14%','broken':'Buyer contract: under 1%–25%+ grades'}],
['1121 Basmati — Contract Milling','basmati','Selected 1121 Basmati requirements can be processed on a seasonal contract basis, subject to paddy availability and buyer specification.','images/Basmati.webp',{'grainLength':'7.4–8.4+ mm','moisture':'12–14% target','broken':'Buyer contract'}],
['Regional Basmati — Contract Milling','basmati','Regional Basmati variants can be considered for seasonal contract milling with buyer-defined quality and packaging requirements.','images/sella.webp',{'grainLength':'7.4–8.4+ mm','moisture':'12–14% target','broken':'Buyer contract'}],
['Bulk Parboiled Rice — 25 kg / 50 kg','sella','Core commercial offering supplied in industrial PP or jute bags. Quantity, grade and packaging are aligned to the order.','images/parboiled.webp',{'grainLength':'Variety dependent','moisture':'12–14% target','broken':'Buyer contract'}],
['Custom Buyer-Spec Rice Milling','custom','Buyer-specific milling for agreed rice varieties, processing, polishing, broken percentage and packaging requirements.','images/image2.webp',{'grainLength':'Specification dependent','moisture':'Contract target','broken':'Contract target'}]
];
await connectDb(); if(!env.mongoUri) throw new Error('MONGODB_URI is required for seed'); await Product.deleteMany({}); await Category.deleteMany({}); await Product.insertMany(products.map(([name,category,description,image,specifications])=>({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),category,description,image,specifications,stock:0,lowStockThreshold:10}))); await Category.insertMany([...new Set(products.map(p=>p[1]))].map(name=>({name,slug:name}))); if(env.adminSeedEmail&&env.adminSeedPassword){const passwordHash=await bcrypt.hash(env.adminSeedPassword,12); await User.updateOne({email:env.adminSeedEmail},{$set:{name:'Local Admin',email:env.adminSeedEmail,passwordHash,role:'admin',status:'active'}},{upsert:true});} await disconnectDb(); console.log('Seed complete');
